# Generated by Django 4.0.5 on 2022-06-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.course'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_file',
            field=models.FileField(blank=True, max_length=255, upload_to='materials'),
        ),
    ]
