# Generated by Django 4.0.5 on 2022-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursematerial_course_coursematerial_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='material_name',
            field=models.CharField(default='DELETED', max_length=255),
        ),
    ]
