# Generated by Django 4.0.5 on 2022-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursematerial_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_name',
            field=models.CharField(max_length=255),
        ),
    ]
