# Generated by Django 4.0.5 on 2022-06-08 15:41

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursematerial_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], max_length=255)),
                ('questions_link', models.CharField(blank=True, max_length=255)),
                ('questions_file', models.FileField(blank=True, max_length=255, upload_to=course.models.custom_upload_to_assignments)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_file',
            field=models.FileField(blank=True, max_length=255, upload_to=course.models.custom_upload_to_materials),
        ),
    ]
