# Generated by Django 4.0.5 on 2022-06-09 10:28

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('course', '0006_assignment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_name', models.CharField(max_length=255)),
                ('practical_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=255)),
                ('questions_link', models.CharField(blank=True, max_length=255)),
                ('questions_file', models.FileField(blank=True, max_length=255, upload_to=course.models.custom_upload_to_practicals)),
                ('lab_room_no', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.faculty')),
            ],
        ),
    ]
