# Generated by Django 4.0.5 on 2022-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
