# Generated by Django 4.0.5 on 2022-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_feedback_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='questions',
            field=models.ManyToManyField(blank=True, to='course.question'),
        ),
    ]
