# Generated by Django 4.0.5 on 2022-07-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_announcement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.feedback')),
            ],
        ),
    ]
