# Generated by Django 4.0.5 on 2022-07-11 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_course_highest_rate_course_rate_1_course_rate_2_and_more'),
        ('course', '0015_feedbackqanda_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.course')),
            ],
        ),
    ]
