# Generated by Django 4.0.5 on 2022-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='personal.course'),
        ),
    ]
