# Generated by Django 4.0.5 on 2022-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_emailrecord_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='highest_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_feedbacks',
            field=models.IntegerField(default=0),
        ),
    ]
