# Generated by Django 4.0.5 on 2022-06-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_dailyattendance'),
        ('student', '0003_remove_student_email_remove_student_enrollment_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('practical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.practical')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
