# Generated by Django 4.0.5 on 2022-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_dailyattendance'),
        ('student', '0004_practicalsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='practicals',
            field=models.ManyToManyField(blank=True, to='course.practical'),
        ),
    ]
