# Generated by Django 4.0.5 on 2022-06-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_emailrecord_enrolled_courses'),
        ('student', '0005_student_practicals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField(default=0)),
                ('total_presents', models.IntegerField(default=0)),
                ('total_absents', models.IntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.course')),
                ('email_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.emailrecord')),
            ],
        ),
    ]
