# Generated by Django 4.0.5 on 2022-06-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_attendancedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedetails',
            name='email_record',
        ),
        migrations.AddField(
            model_name='attendancedetails',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
