# Generated by Django 4.0.5 on 2022-06-23 15:51

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_attendancedetails_email_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='answer_file',
            field=models.FileField(max_length=255, null=True, upload_to=student.models.custom_upload_to_assignments_submissions),
        ),
    ]
