# Generated by Django 4.0.5 on 2022-06-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_assignmentsubmission_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
