# Generated by Django 4.0.5 on 2022-06-24 05:39

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_assignmentsubmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalsubmission',
            name='answer_file',
            field=models.FileField(max_length=255, null=True, upload_to=student.models.custom_upload_to_practicals_submissions),
        ),
        migrations.AddField(
            model_name='practicalsubmission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
